services:
  - type: web
    name: web3-signer-api
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
      - key: CORS_ORIGIN
        sync: false 

